# Book settings
# template from https://github.com/executablebooks/github-action-demo
title: Introducción al Machine Learning
author: <b>Julián Arias</b>/ Universidad de Antioquia -- Labs por Germán E. Melo - Deiry Sofía Navas
copyright: "2026"
logo: Local/imgs/fudea.jpg

repository:
   url: https://github.com/jdariasl/Intro_ML_2025
   branch: master

launch_buttons:
  binderhub_url: ""
  colab_url: https://colab.research.google.com

html:
  google_analytics_id: "UA-51547737-2"

execute:
  execute_notebooks         : off

